CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    is_guest BOOLEAN NOT NULL DEFAULT FALSE,
    ai_trial_count INTEGER NOT NULL DEFAULT 2
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = current_schema() AND table_name = 'users' AND column_name = 'nama_lengkap'
    ) THEN
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = current_schema() AND table_name = 'users' AND column_name = 'full_name'
        ) THEN
            EXECUTE 'UPDATE users SET full_name = nama_lengkap WHERE full_name IS NULL';
            EXECUTE 'ALTER TABLE users DROP COLUMN nama_lengkap';
        ELSE
            EXECUTE 'ALTER TABLE users RENAME COLUMN nama_lengkap TO full_name';
        END IF;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_date TIMESTAMP,
    amount DOUBLE PRECISION,
    category VARCHAR(255),
    payment_method VARCHAR(255),
    description VARCHAR(255),
    input_type VARCHAR(255),
    validation_status VARCHAR(255),
    user_id BIGINT,
    CONSTRAINT fk_receipt_user FOREIGN KEY (user_id) REFERENCES users(id)
);

DO $$
DECLARE
    old_column TEXT;
    new_column TEXT;
BEGIN
    FOR old_column, new_column IN
        SELECT * FROM (VALUES
            ('tanggal', 'transaction_date'),
            ('jumlah', 'amount'),
            ('kategori', 'category'),
            ('merchant', 'payment_method'),
            ('tipe_input', 'input_type'),
            ('status_validasi', 'validation_status')
        ) AS column_names(old_name, new_name)
    LOOP
        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_schema = current_schema()
              AND table_name = 'receipt'
              AND column_name = old_column
        ) THEN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = 'receipt'
                  AND column_name = new_column
            ) THEN
                EXECUTE format(
                    'UPDATE receipt SET %I = %I WHERE %I IS NULL',
                    new_column,
                    old_column,
                    new_column
                );
                EXECUTE format('ALTER TABLE receipt DROP COLUMN %I', old_column);
            ELSE
                EXECUTE format(
                    'ALTER TABLE receipt RENAME COLUMN %I TO %I',
                    old_column,
                    new_column
                );
            END IF;
        END IF;
    END LOOP;
END $$;

ALTER TABLE receipt ADD COLUMN IF NOT EXISTS description VARCHAR(255);
